In [7]:
import projects
import facilities
import users_and_facilities
import users_and_projects

import pandas as pd

In [21]:
# Define years over which compliance data will be considered and where to find it
# FOR UPDATES: add reporting and mrr data and file years


reporting_periods = ["2013-2014", "2015-2017", "2018-2020", "2021-2023", "2024"]
mrr_data_years = ["2024"]
mrr_file_year = {
    "2013": "2019-11-04",
    "2014": "2019-11-04",
    "2015": "2019-11-04",
    "2016": "2020-11-04",
    "2017": "2020-11-04",
    "2018": "2020-11-04",
    "2019": "2020-11-04",
    "2020": "2021-11-04",
    "2021": "2022-11-04",
    "2022": "2023-11-06",
    "2023": "2024-11-15",
    "2024": "2025-11-04"
}

# FOR UPDATES: change to latest issuance table file name
issuance_table_path = "../data/issuance-tables/nc-arboc_issuance_2025-12-15.xlsx"
compliance_report_path = "../data/compliance-reports/"
mrr_data_path = "../data/mrr-data/"

## Check project_df against issuance data

Check that first and last rows of the new issuance table are included in `project_df`.

In [3]:
project_df = projects.read_project_data(issuance_table_path)

In [4]:
project_df

,arb_id,opr_id,project_name,project_type,state,documentation
0,CAOD1007,ACR1007,A-Gas 3-2023B,Ozone Depleting Substance Project,OH,https://acr2.apx.com/mymodule/reg/prjView.asp?...
1,CAMM1009,ACR1009,Green Valley Abandoned Mine Methane Recovery P...,Mine Methane Capture Project,IL,https://acr2.apx.com/mymodule/reg/prjView.asp?...
2,CAMM1011,ACR1011,Marshall County Flare VI,Mine Methane Capture Project,WV,https://acr2.apx.com/mymodule/reg/prjView.asp?...
3,CAOD1013,ACR1013,Tradewater ODS 54,Ozone Depleting Substance Project,OH,https://acr2.apx.com/mymodule/reg/prjView.asp?...
4,CAOD1020,ACR1020,Hudson Tech 2024-1,Ozone Depleting Substance Project,OH,https://acr2.apx.com/mymodule/reg/prjView.asp?...
...,...,...,...,...,...,...
2104,CAMM0121,13,Coal Mine Methane Capture and Use Project at t...,Mine Methane Capture Project,WY,https://www.vcsprojectdatabase.org/#/project_d...
2105,CALS0122,CAR794,Farm Power Lynden Anaerobic Digester,Livestock Project,WA,https://thereserve2.apx.com/mymodule/reg/prjVi...
2113,CAFR0123,CAR730,Usal Redwood Forest,U.S. Forest Project,CA,https://thereserve2.apx.com/mymodule/reg/prjVi...
2115,CALS0124,CAR393,Cottonwood Dairy Livestock Gas Capture Project,Livestock Project,CA,https://thereserve2.apx.com/mymodule/reg/prjVi...
2116,CALS0126,CAR393,Cottonwood Dairy Livestock Gas Capture Project,Livestock Project,CA,https://thereserve2.apx.com/mymodule/reg/prjVi...

## Check facility_df against mrr data

In [7]:
facility_df = facilities.read_facility_data(mrr_data_path, mrr_data_years)

The new reporting period should only include`facility_id`s that appear in the corresponding MRR data sheets. 

If the new reporting period is an annual update (e.g. '2022'), check that the first and last rows of the newest MRR data correspond with the first and last rows associated with the new reporting period in `facility_df`. 

If the new reporting period is an full reporting period update (e.g. `2021-2023`) check that the head of `facility_df` corresponds to facilities any of the corresponding MRR data files, and the tail of `facility_df` corresponds to the latest MRR data. (We only keep the lates instance of each `facility_id` in the dataframe).

In [4]:
facility_df[facility_df["reporting_period"]=="2024"]

,facility_id,facility_name,city,state,sector,reporting_period
0,3006,3 Phases Renewables - EPE,El Segundo,CA,Electricity Importer,2024
1,104356,3M Corona,Corona,CA,Other Combustion Source,2024
2,104903,3PR Trading - EPE,El Segundo,CA,Electricity Importer,2024
3,104927,"4J Energy, LLC",Houston,TX,"Supplier of Natural Gas, NGL, or LPG",2024
4,104796,AAK Richmond,Richmond,CA,Other Combustion Source,2024
...,...,...,...,...,...,...
817,104678,WP&A King,Lost Hills,CA,Other Combustion Source,2024
818,101736,WP&A Lost Hills,Lost Hills,CA,Other Combustion Source,2024
819,104618,"WWF Operating Company, LLC",City Of Industry,CA,Other Combustion Source,2024
820,100322,Yuba City Cogeneration Partners LP,Yuba City,CA,Cogeneration,2024
821,104946,Yuma Cogeneration Associates - EPE,Yuma,AZ,Electricity Importer,2024

## Check user_project_df against compliance report

In [9]:
users_and_projects = users_and_projects.read_user_project_data(compliance_report_path, reporting_periods)

For spot checking the `user_project_df` it's helpful to reference both the latest compliance report and the published version of the compliance users tool. First, subset the dataframe to the newly added reporting period and check that the head and tail match the top and bottom of the `Offset Detail` sheet of the newest compliance report.

In [10]:
users_and_projects[users_and_projects["reporting_period"]=="2024"]

     user_id    arb_id reporting_period  quantity
5     CA1011  CAFR5011             2024      1857
8     CA1011  CAFR5437             2024      1857
35    CA1019  CAFR5034             2024     10253
37    CA1019  CAFR5096             2024     10253
44    CA1019  CAFR5233             2024     10764
...      ...       ...              ...       ...
3357  CA3320  CAMM5675             2024       634
3364  CA3337  CALS5365             2024         1
3371  CA3776  CAFR5226             2024      1382
3375  CA3776  CAOD5419             2024      1382
3377  CA3963  CAFR5212             2024        49

[232 rows x 4 columns]

Second, do some spot checks using the compliance users tool: https://carbonplan.org/research/compliance-users

For a number of random users, check that the tool plus the latest compliance report matches up with the `users_and_projects` dataframe.

In [14]:
users_and_projects[users_and_projects["user_id"]=="CA3320"]

     user_id    arb_id reporting_period  quantity
3350  CA3320  CAFR5038        2021-2023      2300
3351  CA3320  CAFR5038             2024       634
3352  CA3320  CAFR5378        2021-2023      1400
3353  CA3320  CAFR5413        2021-2023      1400
3354  CA3320  CAFR6339        2021-2023      1800
3355  CA3320  CAMM5593        2021-2023      1800
3356  CA3320  CAMM5675        2021-2023      2300
3357  CA3320  CAMM5675             2024       634

# Check user_facility against compliance report

In [15]:
user_facility_df = users_and_facilities.read_user_facility_data(compliance_report_path, reporting_periods)

reporting_period
reporting_period
reporting_period
reporting_period
here
reporting_period
here

Rows associted with the new reporting period in `user_facility_df` should correspond to unique ARB GHG IDs in the `Compliance Summary` tab of the new compliance report.

In [16]:
user_facility_df[user_facility_df["reporting_period"]=="2024"]

,user_id,user_name,facility_id,reporting_period
1718,CA1001,"The Newark Group, Inc.",104136,2024
1719,CA1003,Plumas-Sierra Rural Electric Cooperative,3100,2024
1720,CA1006,"Frito-Lay, Inc.",101235,2024
1721,CA1006,"Frito-Lay, Inc.",104207,2024
1722,CA1011,"San Joaquin Refining Company, Inc.",101239,2024
...,...,...,...,...
2071,CA4038,MFT Energy US Power LLC,104951,2024
2072,CA4041,Plains Midstream Canada ULC,104731,2024
2073,CA4045,"GH Camarillo, LLC",104364,2024
2074,CA4062,"Central Valley Meat Co., Inc.",104743,2024
2075,CA4067,"BHE Renewables, LLC",104946,2024

It's also helpful to spot check a couple of random users (i.e. entities) from the new compliance report against the `user_facility_df` and the existing compliance users tool: https://carbonplan.org/research/compliance-users

For a handful of `user_id`s, check that the tool results plus the new compliance report data match the dataframe.

In [17]:
user_facility_df[user_facility_df["user_id"]=="CA1170"]

     user_id                        user_name facility_id reporting_period
153   CA1170  Southern California Gas Company      100915        2013-2014
154   CA1170  Southern California Gas Company      101346        2013-2014
155   CA1170  Southern California Gas Company      101349        2013-2014
156   CA1170  Southern California Gas Company      101675        2013-2014
157   CA1170  Southern California Gas Company      104220        2013-2014
552   CA1170  Southern California Gas Company        5002        2015-2017
553   CA1170  Southern California Gas Company      100915        2015-2017
554   CA1170  Southern California Gas Company      101346        2015-2017
555   CA1170  Southern California Gas Company      101349        2015-2017
556   CA1170  Southern California Gas Company      101675        2015-2017
557   CA1170  Southern California Gas Company      104220        2015-2017
1001  CA1170  Southern California Gas Company      100915        2018-2020
1002  CA1170  Southern California Gas Company      101346        2018-2020
1003  CA1170  Southern California Gas Company      101349        2018-2020
1004  CA1170  Southern California Gas Company      101675        2018-2020
1005  CA1170  Southern California Gas Company        5002        2018-2020
1423  CA1170  Southern California Gas Company        5002        2021-2023
1424  CA1170  Southern California Gas Company      100915        2021-2023
1425  CA1170  Southern California Gas Company      101675        2021-2023
1824  CA1170  Southern California Gas Company        5002             2024
1825  CA1170  Southern California Gas Company      100915             2024
1826  CA1170  Southern California Gas Company      101675             2024

For a handful of `facility_id`s that appear in the new compliance report, check that the tool results plus new compliance report data match the dataframe.

In [20]:
user_facility_df[user_facility_df["facility_id"]=="101498"]

     user_id                         user_name facility_id reporting_period
193   CA1225  The Morning Star Packing Company      101498        2013-2014
592   CA1225  The Morning Star Packing Company      101498        2015-2017
1035  CA1225  The Morning Star Packing Company      101498        2018-2020
1454  CA1225  The Morning Star Packing Company      101498        2021-2023
1853  CA1225  The Morning Star Packing Company      101498             2024

That should do it! 

If all of those checks pass, run `build_users_data.py`. Update the methods doc with any data anomolies reported by the script: https://docs.google.com/document/d/1DZT6bWENq4EZ_BAnscwMWN-Tc1ketSiWeEQ3hhSmi10/edit?tab=t.0

## Sandbox

Keep any other testing down here!

In [14]:
name, info = facilities.make_facility_info(facility_df, user_facility_df)

Facilities that appear in compliance data but not contemporary MRR data:
-----> 101492, 2015-2017
-----> 101492, 2018-2020
-----> 100335, 2015-2017
-----> 100335, 2018-2020
-----> 101258, 2015-2017
-----> 101223, 2015-2017

In [20]:
facility_df[facility_df['reporting_period']=='2021-2023']

,facility_id,facility_name,city,state,sector,reporting_period
6545,104869,Baldwin Park Resident Owned Utility District (...,Baldwin Park,CA,Electricity Importer,2021-2023
6580,104411,"California Dairies, Inc. Artesia",Artesia,CA,Other Combustion Source,2021-2023
6751,104459,ExxonMobil POPCO Facility,Goleta,CA,Oil and Gas Production,2021-2023
6758,104091,Seneca San Joaquin Production Facilities,Fellows,CA,Oil and Gas Production / Supplier of Natural G...,2021-2023
6814,100323,Ingredion Incorporated Stockton Plant,Stockton,CA,Other Combustion Source,2021-2023
...,...,...,...,...,...,...
8977,104679,WP&A Firebaugh,Firebaugh,CA,Other Combustion Source,2021-2023
8978,104678,WP&A King,Lost Hills,CA,Other Combustion Source,2021-2023
8979,101736,WP&A Lost Hills,Lost Hills,CA,Other Combustion Source,2021-2023
8980,104618,"WWF Operating Company, LLC",City Of Industry,CA,Other Combustion Source,2021-2023
8981,100322,Yuba City Cogeneration Partners LP,Yuba City,CA,Cogeneration,2021-2023

In [23]:
users_and_projects[users_and_projects["reporting_period"]=="2021-2023"]['arb_id'].nunique()

278

In [31]:
users_and_projects[users_and_projects["reporting_period"]=="2021-2023"].groupby('arb_id')['quantity'].sum().sort_values(ascending=False).head(10)

arb_id
CAFR5437    3501681
CAFR6339    1369922
CAFR6314    1185535
CAFR6381     862849
CAFR5297     772378
CAFR5291     630982
CAFR5090     530545
CAFR5281     516523
CAFR5208     420327
CAFR5225     401047
Name: quantity, dtype: int64

In [41]:
users_and_projects

     user_id    arb_id reporting_period  quantity
0     CA1000  CAOD0074        2013-2014      7360
1     CA1000  CAOD5013        2013-2014     10240
2     CA1006  CAFR5305        2018-2020     18723
3     CA1006  CAFR5305        2021-2023      3930
4     CA1006  CAFR6382        2021-2023      3930
...      ...       ...              ...       ...
3141  CA3776  CAFR5226        2021-2023      1043
3142  CA3776  CAFR5230        2021-2023       918
3143  CA3776  CALS5030        2021-2023      1477
3144  CA3776  CAOD5419        2021-2023      3439
3145  CA3850  CAFR5425        2021-2023       126

[3146 rows x 4 columns]

In [39]:
    opr_to_arbs, combined_arbs = projects.make_opr_to_arbs(project_df)
    arb_to_oprs = projects.make_arb_to_oprs(project_df, combined_arbs)
    project_name_to_opr, opr_to_project_info = projects.make_project_info(project_df)

In [51]:
credits_used = users_and_projects[users_and_projects["reporting_period"]=="2021-2023"].groupby('arb_id')['quantity'].sum().reset_index()
credits_used

       arb_id  quantity
0    CAFR0041     56916
1    CAFR0049     59846
2    CAFR0058      2767
3    CAFR0102     12539
4    CAFR0123    202719
..        ...       ...
273  CAOD6498     60731
274  CAOD6560     59147
275  CAOD6578     75000
276  CAOD6662     32777
277  CAOD6860     45265

[278 rows x 2 columns]

In [66]:
# Convert JSON to a DataFrame
json_df = pd.DataFrame.from_dict(opr_to_project_info, orient='index')
json_df = json_df['project_type'].reset_index()

In [67]:
json_df

       index                       project_type
0    ACR1007  Ozone Depleting Substance Project
1    ACR1013  Ozone Depleting Substance Project
2    ACR1020  Ozone Depleting Substance Project
3    ACR1022  Ozone Depleting Substance Project
4    ACR1040  Ozone Depleting Substance Project
..       ...                                ...
609   CAR891       Mine Methane Capture Project
610       13       Mine Methane Capture Project
611   CAR794                  Livestock Project
612   CAR730                U.S. Forest Project
613   CAR393                  Livestock Project

[614 rows x 2 columns]

In [79]:
opr_to_arbs_df = pd.DataFrame.from_dict(opr_to_arbs, orient='index')
opr_to_arbs_df.index.name = 'opr_id'
opr_to_arbs_df

                         0
opr_id
ACR1007           CAOD1007
ACR1013           CAOD1013
ACR1020           CAOD1020
ACR1022           CAOD1022
ACR1040           CAOD1040
...                    ...
CAR891            CAMM0120
13                CAMM0121
CAR794            CALS0122
CAR730            CAFR0123
CAR393   CALS0124-CALS0126

[614 rows x 1 columns]

In [73]:
opr_to_arbs_df

                         0
ACR1007           CAOD1007
ACR1013           CAOD1013
ACR1020           CAOD1020
ACR1022           CAOD1022
ACR1040           CAOD1040
...                    ...
CAR891            CAMM0120
13                CAMM0121
CAR794            CALS0122
CAR730            CAFR0123
CAR393   CALS0124-CALS0126

[614 rows x 1 columns]